PointOfSale/Controllers/AccessController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using PointOfSale.Business.Contracts;
using PointOfSale.Model;
using PointOfSale.Models;
using System.Security.Claims;

namespace PointOfSale.Controllers
{
    public class AccessController : Controller
    {
        private readonly IUserService _userService;


        public AccessController(IUserService userService)
        {
            _userService = userService;

        }

        public IActionResult Login()
        {
            ClaimsPrincipal claimuser = HttpContext.User;
            if (claimuser.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(VMUserLogin model)
        {
            User user_found = await _userService.GetByCredentials(model.Email, model.PassWord);

            if (user_found == null)
            {
                ViewData["Message"] = "No matches found";
                return View(model);
            }

            ViewData["Message"] = "";

            List<Claim> claims = new List<Claim>()
                {
                    new Claim(ClaimTypes.Name, user_found.Name),
                    new Claim(ClaimTypes.NameIdentifier, user_found.IdUsers.ToString()),
                    new Claim(ClaimTypes.Role,user_found.IdRol.ToString()),
                    new Claim("Email",user_found.Email),
                };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            AuthenticationProperties properties = new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = model.KeepLoggedIn
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), properties);

            return RedirectToAction("Index", "Home");


        }
    }
}


//using Microsoft.AspNetCore.Authentication;
//using Microsoft.AspNetCore.Authentication.Cookies;
//using Microsoft.AspNetCore.Mvc;
//using PointOfSale.Business.Contracts;
//using PointOfSale.Model;
//using PointOfSale.Models;
//using System.Security.Claims;

//namespace PointOfSale.Controllers
//{
//	public class AccessController : Controller
//	{
//		private readonly IUserService _userService;

//		public AccessController(IUserService userService)
//		{
//			_userService = userService;
//		}

//		public IActionResult Login()
//		{
//			if (User.Identity.IsAuthenticated)
//				return RedirectToAction("Index", "Home");

//			return View();
//		}

//		[HttpPost]
//		public async Task<IActionResult> Login(VMUserLogin model)
//		{
//			User userFound = await _userService.GetByCredentials(model.Email, model.PassWord);

//			if (userFound == null)
//			{
//				ViewData["Message"] = "No matches found";
//				return View();
//			}

//			List<Claim> claims = new List<Claim>()
//			{
//				new Claim(ClaimTypes.Name, userFound.Name),
//				new Claim(ClaimTypes.NameIdentifier, userFound.IdUsers.ToString()),
//				new Claim(ClaimTypes.Role, userFound.IdRol.ToString()),
//				new Claim("Email", userFound.Email),
//			};

//			ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

//			await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

//			return RedirectToAction("Index", "Home");
//		}
//	}
//}

PointOfSale/Views/Access/Login.cshtml
@model PointOfSale.Models.VMUserLogin;
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Sleek Dashboard - Free Bootstrap 4 Admin Dashboard Template and UI Kit. It is very powerful bootstrap admin dashboard, which allows you to build products like admin panels, content management systems and CRMs etc.">

    <title>Sign In - Sleek Admin Dashboard Template</title>

    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500|Poppins:400,500,600,700|Roboto:400,500" rel="stylesheet" />
    <link href="https://cdn.materialdesignicons.com/4.4.95/css/materialdesignicons.min.css" rel="stylesheet" />

    <!-- SLEEK CSS -->
    <link id="sleek-css" rel="stylesheet" href="~/css/sleek.css" />

  </head>

  <body class="" id="body">
    <div class="container d-flex align-items-center justify-content-center vh-100">
      <div class="row justify-content-center">
        <div class="col-lg-6 col-md-10">
          <div class="card">
            <div class="card-header bg-primary">
              <div class="app-brand">
                <a href="#">
                  <span class="brand-name">Sales</span>
                </a>
              </div>
            </div>

            <div class="card-body p-5">
              <h4 class="text-dark mb-5">Sign In</h4>
              
              <form  asp-controller="Access" asp-action="Login" method="post">
                <div class="row">
                  <div class="form-group col-md-12 mb-4">
                    <input type="email" class="form-control input-lg" asp-for="Email" placeholder="Email">
                  </div>

                  <div class="form-group col-md-12 ">
                    <input type="password" class="form-control input-lg" asp-for="PassWord" placeholder="Password">
                  </div>

                  <div class="col-md-12">
                    <div class="d-flex my-2 justify-content-between">
                      <div class="d-inline-block mr-3">
                        <label class="control control-checkbox">Keep me logged In.
                          <input type="checkbox" asp-for="KeepLoggedIn" />
                          <div class="control-indicator"></div>
                        </label>
                      </div>
                    </div>

                    <button type="submit" class="btn btn-lg btn-primary btn-block mb-4">Sign In</button>

                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>



    <!-- Javascript -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>
</html>